### ISSUE TITLE
douban插件下载了却不能显示

### ISSUE THREAD

**Issue by liboyue23** [Yikun/hexo-generator-douban#4]
我用npm下载了你的插件，
![image](https://cloud.githubusercontent.com/assets/11264082/13425567/b429f2a8-dfe2-11e5-84f0-a3fe6ff46e6a.png)

而且也在_config.yml配置好了，然后该怎么做才能显示我豆瓣图书清单呢？
![image](https://cloud.githubusercontent.com/assets/11264082/13425564/a7d1371e-dfe2-11e5-898c-24d7356b2f7b.png)

**Comment by Yikun** [comment]
需要在主题的配置一下menu中的douban，例如可以参考我的主题[_config.yml](https://github.com/Yikun/hexo-theme-yilia/blob/master/_config.yml)：

```
// ... ...
# Header
menu:
  主页: /
  文章: /archives
  随笔: /tags/随笔/
  项目: /project
  读书: /douban
// ... ...
```

**Comment by liboyue23** [comment]
像你这样，我在_config.yml里设置了menu：
![image](https://cloud.githubusercontent.com/assets/11264082/13486672/e820735e-e14d-11e5-9378-879bc849cba2.png)
但是我对应的/douban目录该怎么生成？不然的话连接根本找不到/douban啊

**Comment by Yikun** [comment]
hexo g或者hexo s，页面生成时，会自动调douban插件生成douban页面的，不需要额外操作。

**Comment by liboyue23** [comment]
然而并没有生成/douban这个目录啊，还是我用命令$ hexo new page "douban"才生成这个目录的，否则都没办法访问这个链接，是不是插件有问题啊？

**Comment by liboyue23** [comment]
按照你说的那样只用hexo g 最后点读书
![image](https://cloud.githubusercontent.com/assets/11264082/13517110/4da1cf40-e1fb-11e5-95cc-95c8dabcc90e.png)
访问的结果是
![image](https://cloud.githubusercontent.com/assets/11264082/13517084/2889aba6-e1fb-11e5-9d57-ed26b1ba8c86.png)

**Comment by Yikun** [comment]
因为信息有限，从截图上应该是你环境配置的问题，你可以尝试着一下下面的步骤来测试一下自己的环境：
下面的指令来自于[hexo官网](https://hexo.io/)

### 1. 安装官方环境和依赖

```
# 安装hexo
npm install hexo-cli -g
# 初始化博客
hexo init blog
cd blog
# 安装依赖
npm install
# 尝试运行
hexo server
```

### 2. 安装豆瓣插件：

在blog目录下

```
npm install hexo-generator-douban --save
```

此时blog下的node_modules文件夹下应该插件已经安装上了，并且在blog下的package.json中可以看到依赖信息:

``` json
# cat package.json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.2.0"
  },
  "dependencies": {
    "hexo": "^3.0.0",
    "hexo-generator-archive": "^0.1.0",
    "hexo-generator-category": "^0.1.0",
    "hexo-generator-douban": "^0.1.1",
    "hexo-generator-index": "^0.1.0",
    "hexo-generator-tag": "^0.1.0",
    "hexo-renderer-ejs": "^0.1.0",
    "hexo-renderer-marked": "^0.2.4",
    "hexo-renderer-stylus": "^0.2.0",
    "hexo-server": "^0.1.2"
  }
}
```

### 3. 配置douban插件

blog（注意是博客的配置而不是主题的配置）的_config.xml加入豆瓣插件的配置

``` yaml
douban:
  user: 83045141
```

### 4. 生成或运行

```
hexo g
```

可以看到下面的信息：

> INFO  Start processing
> INFO  Files loaded in 327 ms
> INFO  Generated: index.html
> **INFO  Generated: douban/index.html**
> INFO  Generated: archives/index.html
> INFO  Generated: fancybox/blank.gif
> INFO  Generated: fancybox/jquery.fancybox.css
> INFO  Generated: fancybox/jquery.fancybox.js
> INFO  Generated: fancybox/jquery.fancybox.pack.js
> INFO  Generated: fancybox/fancybox_overlay.png
> INFO  Generated: fancybox/fancybox_loading@2x.gif
> INFO  Generated: fancybox/fancybox_loading.gif
> INFO  Generated: fancybox/fancybox_sprite@2x.png
> INFO  Generated: fancybox/fancybox_sprite.png
> INFO  Generated: archives/2016/03/index.html
> INFO  Generated: archives/2016/index.html
> INFO  Generated: css/fonts/FontAwesome.otf
> INFO  Generated: fancybox/helpers/jquery.fancybox-buttons.css
> INFO  Generated: js/script.js
> INFO  Generated: css/style.css
> INFO  Generated: fancybox/helpers/jquery.fancybox-thumbs.js
> INFO  Generated: fancybox/helpers/jquery.fancybox-buttons.js
> INFO  Generated: fancybox/helpers/jquery.fancybox-thumbs.css
> INFO  Generated: css/fonts/fontawesome-webfont.woff
> INFO  Generated: css/fonts/fontawesome-webfont.eot
> INFO  Generated: fancybox/helpers/fancybox_buttons.png
> INFO  Generated: fancybox/helpers/jquery.fancybox-media.js
> INFO  Generated: css/fonts/fontawesome-webfont.svg
> INFO  Generated: css/images/banner.jpg
> INFO  Generated: css/fonts/fontawesome-webfont.ttf
> INFO  Generated: 2016/03/04/hello-world/index.html
> INFO  29 files generated in 715 ms

**Comment by liboyue23** [comment]
好了，谢谢博主耐心帮助，感谢！

**Comment by Yikun** [comment]
Enjoy it!
