### ISSUE TITLE
我的豆瓣看书信息突然拉不下来了

### ISSUE THREAD

**Issue by GuoJinyu** [Yikun/hexo-generator-douban#6]
http://guojinyu.github.io/douban/
源于前几天我试着用Windows PowerShell（之前用Git Bash） hexo g,hexo d了一下,然后看书信息就没有了。
之后再用Git Bash，依旧如此。
所以，我现在不确定是我这里的问题还是插件的问题。
kun神有空确认下。

**Comment by Yikun** [comment]
恩，豆瓣API的http服务不可用了，我切到https了

已经更新发布新版本的了，升级到0.1.12版本吧~
更新"hexo-generator-douban": "^0.1.2"，然后重新npm install就好。
（淘系cnpm install速度更快，可以看看，http://npm.taobao.org/，哈哈）

**Comment by Yikun** [comment]
Fixed
