### ISSUE TITLE
我在大佬代码的基础上加了点东西，希望大家能一起交流学习^.^

### ISSUE THREAD

**Issue by mythsman** [Yikun/hexo-generator-douban#8]
我的小代码:[hexo-douban](https://github.com/mythsman/hexo-douban)
我的小博客:[mythsman](https://blog.mythsman.com)

**Comment by forvoid** [comment]
谢谢你的思路

**Comment by mythsman** [comment]
@forvoid 互相学习哈~

**Comment by Yikun** [comment]
赞，才发现这个issue，之前，没有向官方贡献出来，主要是因为觉得各个主题中的CSS的适配比较头疼。
